[package]
name = "conduit-op-reth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "conduit-op-reth"
path = "src/main.rs"

[dependencies]
conduit-op-reth-node.workspace = true

reth-ethereum-cli.workspace = true
reth-optimism-consensus.workspace = true
reth-optimism-node.workspace = true
reth-node-builder = { workspace = true, features = ["op"] }
reth-node-core.workspace = true
reth-db.workspace = true
reth-cli-util.workspace = true

clap.workspace = true
tracing.workspace = true

[build-dependencies]
vergen = { version = "9.1", features = ["build", "cargo", "emit_and_set"] }
vergen-git2 = "9.1"

[dev-dependencies]
conduit-op-reth-node.workspace = true
reth-cli.workspace = true
reth-e2e-test-utils.workspace = true
reth-node-api.workspace = true
reth-node-builder = { workspace = true, features = ["test-utils"] }
reth-node-core.workspace = true
reth-payload-primitives.workspace = true
reth-payload-builder.workspace = true
reth-tasks.workspace = true
reth-optimism-node = { workspace = true, features = ["test-utils"] }
reth-provider.workspace = true
reth-storage-api.workspace = true
alloy-primitives.workspace = true
alloy-genesis.workspace = true
alloy-rpc-types-engine.workspace = true
alloy-eips.workspace = true
reth-optimism-chainspec.workspace = true
reth-primitives-traits.workspace = true
serde_json.workspace = true
eyre.workspace = true
tokio.workspace = true
reth-tracing.workspace = true
alloy-signer-local.workspace = true
alloy-network.workspace = true
alloy-consensus.workspace = true
alloy-rpc-types-eth.workspace = true
alloy-sol-macro.workspace = true
alloy-sol-types.workspace = true
reth-chainspec.workspace = true
reth-rpc-eth-api.workspace = true
tempfile.workspace = true
